spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a1_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED